language: swift
osx_image: xcode11.2
xcode_project: MacMagazine.xcodeproj
xcode_scheme: MacMagazine
xcode_destination: platform=iOS Simulator,OS=13.2.2,name=iPhone 11 Pro
before_install:
- |
  brew update
  brew install swiftlint
  gem install xcpretty -N --no-ri --no-doc
  gem update fastlane
script:
- |
  set -o pipefail
  xcodebuild clean analyze test -project {xcode_project} -scheme {xcode_scheme} -destination {xcode_destination} | xcpretty
after_success:
- "./scripts/testflight.sh"
env:
  global:
  - secure: OWHe2Qf8cDedYLaN98qNct/8AgCuOZJyddjtiikZhteXzmSvaTet6oVPWmhlfpPl4l71EEQBC0bNi2pZoZKrwc5TzsiWFAq2uUR3cW9JtVKkxvcMRDTbi1mDH2B2CNbo4JmNoA/hksnau9cp1P3rojURDyOMbT3Dv3JYz2c/TpwTuKWPubiNBe0VCxueZ06ElNaX51ayEtJUv8xyEpqc9nvi1blxotjv7V/JYjCm7X6dvDRFVq7OYQuQH51mWxdMrtxuCGhzB6kFYq4uYlByPUmVUbffCu9Zqf5npdMUWW9B9Mu8sWgiwL2clze10TC+nbXlTWmfdL+bDF6GD1zIJd06bf/LZy5vX92DpGB0alL1g79HILpUa3RisqEwu2yGM1EJ+7Q7UcWPL43NI1qfFSZ4aruf6t3PaHPlKPenB/s/gBZtmAtKAoowzHbRuxzyVHKqB/ic/w9X7GoLbACenlStpvTZ1TmQ7TGvf7vN57dWuhvZ0vOOgs4igZs6O9d2b84H4B8lsKVEST9EQ+/BWQnCRacw1JxC8bgP+X1boPdpaJdZ0LHrDGRVOFoFbiqdg3PSBbbmCJwe9iyEcZkqL0Yg+8LDMPmFtV0CNEdCdV48w++l1/MVzlTYoNPz5MxIUMcpP01iV4a6wPSW4VCPFNe8PcouDhgVNxcAMtUE0lU=
  - secure: FeBqTe41GYw4ec6obOdbcU5wF0xWYokum9QSk1zDGjNojwJXkz/Q9ZcnRDupLg3NSM/YRYcOrOi3blbjlvtP8xb0etb+b1bAxyOw4uS6JGsXH4kl3IiZMxI4Fpwsy/5YpKfsDy7uXV+UkffFePLMltTfObjdL5jaBZYergJpQA7GdkAlLj2kfgnTSJ4I+N8TMlfyhZCfgRnoA414cryvqbq8rz148ZbPeSSTvbdsGXSDDYvTDbqTC9VEIyoZdOdXDRClXI0+zow06CQpGqW+f9w1D6n0TvAgi518bNJem2bvs/v7l4VdXzmzbf2R10yCR2rP/O9gSYoQ0Kq2mmQtT4bFUuSsD9BqmliSD2khWGy96xCee+y8VOLF/KwK3kHmcXm/UDROEdI6PS7SlIJmbmIQ7VWcdEiymfosi32C3U2gijgdcDiSt03qpPAIRD9Tn23p+GSVouHDE/cQdJg2tHUQCZmyOSn3omSY/3boj1sQtNqdPdYF14atiAlJQp9DfCMSax30Bmf/odsHZJWmoWZvYKWkseN0OXRX1t/Z7ARJU+D39e215oo/Us5Olv95iMIKCAlCERr0zIosbj9pqgl97G5YLqg7ZeBxy0fy/d9++HrCRZYfbZEbgHGZuK5yiykkY4UOcl3MbVOaTHz6Vm1rX9Go420Z+8uz2iwhE7k=
