language: swift
osx_image: xcode11.2
env:
  global:
  - COMPANY="Brit Solucoes Integradas de Tecnologia Ltda."
  - COMPANY_ID="7PXVC8PJ97"
  - APP_NAME="MacMagazine"
  - 'DEVELOPER_NAME="iPhone Distribution: $COMPANY ($COMPANY_ID)"'
  - PROFILE_NAME="MacMagazine"
  - DESTINATION="platform=iOS Simulator,OS=13.2.2,name=iPhone 11 Pro"
  - BRANCH="release/4.0"
  - secure: LuORckBjf0QV1QFYzWbnV21GBjIyrQXDnDIDYRTGkxLc62pqLXFDhdr0mPRTSKlxl2kDoYNbGGStcFRaiukoYfI/AFp3UKycV5qpAeBiQpseR1MdwWe2disyUmYvqXlk+n5lvP41P8P+J5nRek0Kv5UdLU6V36bS60/7Ho73wTPItFEx8Oj/BTJlMOYkuSmKoE7pCzvd4XrX3+bgPNjgWL98eA89adi9EOqUqRs39mtvPqxV8zf8rJ90iCXNopaL3WMy2DVYoVjw28s4TXZiI1ROy569MPSbi7jLTv/RifoC7+1+xYEiZVL7gZ80dIqi/OwwnDXf1l7gSqETGjSe0oNTnGBbN0zDD7AiRRqNESXOEMz9iX0avLozc5jXCKlj19eI6qStAibaoFsIsG/I2NNDfstbgHVb/J60sSfoygSsj5d6hp6FlIZjHxjmwmgj4kkJi3VYyFser0UpeK7R6HosHQLa4akSeJsSyuKokvQ44nhLTmOkn9WzWGwUr0RnUDGdOxalGERchvSX9Ee6zuaYG41GET9mhQiqZWyRFEnI38WSTDZzWlp2lxwRNHcR2roJe0RDmpUmJZ7902+ILAjM1uMIhu9pMd/32QteAtE3CVejTjjxgalcxEKyXvQ2ZzhyaH3YHfweS57tzDUHDfiN1vXesIH6QmTAAM7stmM=
  - secure: qRI0c5ssdJfqg54SQRf7TVJ5+QA26r2f3SqVFoFhIyZaAfkoa4HH1coozXswvfKwAQxRrOb8dvKUNvWKwmSxO6ja2H422zxy7W2V1yFJoxUwQ4tDLXxz7SpmPVzJn8FUSvBKtPQd5CFta1Vs23/BoC4zWeWdw12/YVpYhb9RZsksSz/Iiv0s04ENxrOnqDBkFGPICKeM+3z/uMGjpzlJdJmVCF11ZQD6uKZzoU1DJ+GpFlPEsvuXOIOJhNueA23RSmnRuboOrvwl8Tl5FpU35LBB4i6OYhSbeBPvud+IhSHGlrX9bGIDbHANRJdxPKgqZ7fMOFVvNcxvDagv+ZsMsbV+qzDc7FlPAHKDSSFiCeEqR7TP+2OrxT7/suO6DHnksRgenuBrewv5f9UCr2C62UJNwas8GL2IZxAilO9tn7lI2Cu6wXUYFJVMRrQRsx9CSLdrJi0gPfz7fybZhWjtY3qMR6y7TVGtx4NNIO8JjXscUARTtYKDyF/7AYRYZbp6e6qLmFu0fQEZz9gS87kgkd8h1y9hV1MmVhDzYZC1LRm9+JNKzsjhF/i9tZAvdofsZUif8qq4ahzbiayrTiqKeFr5bvucedwL2LA15NqEAcP78nLBm4e+jTjxdu5gNwL2E6IgKOvOBYpE6K8kuJ+RiJ4E1op4cDEKzVr9ORvePpQ=
jobs:
  include:
  - stage: test
    script:
    - xcodebuild clean analyze test -project "$APP_NAME".xcodeproj -scheme "$APP_NAME"
      -destination "$DESTINATION"
  - stage: deploy
    before_script:
    - openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.cer.enc -d
      -a -out scripts/certs/dist.cer
    - openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.p12.enc -d
      -a -out scripts/certs/dist.p12
    script:
    - "./scripts/add-key.sh"
    - "./scripts/bundle.sh"
stages:
- name: test
  if: type = pull_request
- name: deploy
  if: type = push AND branch = release/4.0
